### ISSUE TITLE
Battery Percentage wrong on OS X

### ISSUE THREAD

**Issue by danbotinger** [sebhildebrandt/systeminformation#103]
### Issue Type

* [x] Bug
* [ ] Feature Request
* [ ] Question

### Expected behavior 

- On OS X, the battery charge percentage should not be gathered via currentcapacity / maxcapacity
- 
- 

### Actual behavior

- Battery percentage returned does not always match with the percentage displayed by system
- 
- 

### Steps to reproduce the problem

- In terminal, enter ioreg -l | grep "Capacity"
- In some cases, CurrentCapacity does not exactly equal MaxCapacity and OS X still shows that the battery is loaded 100%
- 

### Specifications 

- package version: 5.6.0
- operating system: darwin(OS X)
- hardware: x86_64

### Problem and possible solution

The percentage could be gathered via pmset -g batt, not sure if this is the best way though.

**Comment by sebhildebrandt** [comment]
Thank you. Will check it later today.

**Comment by sebhildebrandt** [comment]
Ok, I already implemented a version that reflects your suggestion. Thank you again! I need to test it later on two other machines and will then publish a new version.

**Comment by sebhildebrandt** [comment]
Just pushed a new version with a fix for that - v3.33.18
Please have a look at it and just tell me if it works on you machine.

**Comment by danbotinger** [comment]
Yes, it is returning the correct percentage now. Thanks!

**Comment by Blatman** [comment]
FWIW I was trying out a sample battery app that uses the systeminformation module and had the same issue - no percentage/broken. Downloaded the latest and it was still broken - percent was 0% and hasbattery returning false all the time. Maybe I am missing something but I have attached a screenshot of the working app after some mods - line 87 seems to filter out the internalbattery parsing (no = in stdout) and the axing of the currentcapacity line kills the code on line 103-105.
This was on MBP with Yosemite BTW

![screen shot 2018-02-08 at 14 21 32](https://user-images.githubusercontent.com/11089335/35978952-f119f570-0cde-11e8-9228-906de1aa7712.png)

Cheers

**Comment by sebhildebrandt** [comment]
I need to have a look later ... in the meanwhile, can you provide the output of the underlying shell command (see line 83). Just to be sure that we are on the “same page” ;-)

Thank you in advance!

**Comment by Blatman** [comment]
Sure Seb -

Line 83
exec("ioreg -n AppleSmartBattery -r | grep '\"CycleCount\"';ioreg -n AppleSmartBattery -r | grep '\"IsCharging\"';ioreg -n AppleSmartBattery -r | grep '\"MaxCapacity\"';ioreg -n AppleSmartBattery -r | grep '\"CurrentCapacity\"';pmset -g batt | grep %", function (error, stdout) {


Log of stdout -

"CycleCount" = 224
      "IsCharging" = No
      "MaxCapacity" = 6211
      "CurrentCapacity" = 1445
 -InternalBattery-0	23%; discharging; 1:00 remaining


The sample app code calling the systeminformation module -
var si = require('systeminformation');

console.log("SI " + si);
// Create a function that can be continuosly called to get updated batter info
function updateData () {
    // Access the battery API of si and pass in a callback function
    si.battery(function (data) {
        // Force the value of updatedInfo in our Vue app to false,
        // this will show the text "Updated" on the page.
        app.updatedInfo = false;
        // Update the data in our Vue app with the data from si
        app.percent = data.percent;
        console.log("Percent  " + data.percent)
        app.isCharging = data.ischarging;
        console.log("Charging " + data.ischarging)
        app.cycles = data.cyclecount;
        console.log("Cycles " + data.cyclecount)
        // To force a CSS animation to occur we wait 1 second
        setTimeout(function () {
            // Then re-add the class of "updated" on the page so the text fades away
            app.updatedInfo = true;
        }, 1000);
    });
}

Cheers.
Yosemite 10.10.5

**Comment by sebhildebrandt** [comment]
Perfect, thank you! 

I made some changes also on that part of the code yesterday while working on first FreeBSD implementation. As I still need to work on finishing the FreeBSD tests, I will provide a new version this weekend. I will reply again when I published it and will ask you to give it another try. OK for you?

**Comment by Blatman** [comment]
Yeah that's fine - the screenshot above shows the code that works OK.

**Comment by Blatman** [comment]
OK, I see the rev has bumped a few times - the version above was 3.33.15 pre-BSD work and I just tried 3.37.1 from GitHub and found the Darwin section in battery.js revamped somewhat.
Anyway still got the problem of percentages not rounded (eg: 94.479246%) if the last part of the ternary in line 117 is used and line 107 is never evaluated because there is no '=' in the line.

The stdout has altered slightly with 3.37.1 - shows as -
"MaxCapacity" = 6276
      "CurrentCapacity" = 5963
      "CycleCount" = 226
      "IsCharging" = Yes
      "DesignCycleCount9C" = 1000
 -InternalBattery-0	95%; charging; 0:27 remaining

To get it going I did -

          let percent = -1;
          if (stdout) {  // new
            var line = lines[5];  // new
            let parts = line.split(';');
            result.charged = parts[1].trim();  //new
            if (parts && parts[0]) {
              let parts2 = parts[0].split('\t');
              if (parts2 && parts2[1]) {           	
                result.percent = parseFloat(parts2[1].trim().replace('%', ''));
              }
            }
          } else { // stdout not exist if no battery on mac
            result.cyclecount = 0;
            result.ischarging = false;
            result.maxcapacity = 0;
            result.currentcapacity = 0;
            result.percent = 0;
            result.charged = '';
            result.hasbattery = false;
          }

          if (result.maxcapacity && result.currentcapacity) {
            result.hasbattery = true;
            result.percent = percent !== -1 ? percent : Math.round(100.0 * result.currentcapacity / result.maxcapacity); // mod
          }
          if (callback) { callback(result); }
          resolve(result);


Note: I added -
  result.charged = parts[1].trim() to capture the charged/charging/discharging status

Cheers.

**Comment by sebhildebrandt** [comment]
Hi @Blatman

Thank you for testing again and thank you for your solution! I tried it here and found out this also has some issues. The `-InternalBattery-0...` line is not necessarily line 5. So I did it slightly different. 

Concerning `result.charged`: is this necessary as a seperate property? "Charged" should be the same as `percent = 100`, right? So I guess there is no seperate property needed. What do you think?

I published my solution (v3.37.2) seconds ago. Maybe you give it a try.

**Comment by Blatman** [comment]
Hi Seb,

yeah I only added the result.charged because I wanted to reflect the data that was presented in the line but yes 100% could be used.

I have noticed that the Mac output can be a bit flaky since often the stdout will say 97% and charged or suchlike so the mac charged statement may not necessarily coincide with 100% (at one point I had 95% and charged showing and of course the Mac never went beyond 95% so 100% would never be reached) - in this case using the charged option would reflect the Mac's opinion on whether the battery is charged or not.

Just tried 3.37.2 and it is fine - line 108 is a lot better than using line[5].

Cheers,

Blane
