### ISSUE TITLE
On windows cpuTemperature() returns -1

### ISSUE THREAD

**Issue by MeesMaas** [sebhildebrandt/systeminformation#76]
Using the following code:
```
si.cpuTemperature()
    .then(data => {
        console.log(data);
});
```

**Comment by sebhildebrandt** [comment]
Hi, 

Please be sure to check 2 things:
- for some versions of windows you need to run this with admin privileges to get proper results. 
- and your hardware platform also needs to support this. To check this, try to run `wmic /namespace:\\root\wmi PATH MSAcpi_ThermalZoneTemperature get CriticalTripPoint,CurrentTemperature /value` in a console.

**Comment by MeesMaas** [comment]
Well that command returns as following:

```
CriticalTripPoint=3782
CurrentTemperature=3010

CriticalTripPoint=3782
CurrentTemperature=3030
```

But running my application as admin still doesnt work. It always returns the same value..

**Comment by sebhildebrandt** [comment]
Thank you for checking it! So to understand you correctly: when you run the command (with out admin privileges) it returns valid values, but the node-code returns only -1 (with or without admin privileges), right? I will recheck it here on my side. Is it ok to ask you later to run some code snippets on your machine if I cannot reproduce it on my machines?

**Comment by sebhildebrandt** [comment]
I made some investigation on my machines and I am not sure, if I can reproduce it. 

To be more clear: I discovered a bug that the max value was always -1. If this is what you mean, the is now corrected and published (v3.30.4). But if you are getting something like this back (with or without admin privileges) 

```
{ main: -1, cores: [], max -1 }
```

while the underlying command works, that is suspicious. On my machines I get the upper result without admin privileges but a correct output with admin rights. I made a little modification parsing the results, maybe this solved the problem. Can you post once again the full output of your code?

**Comment by MeesMaas** [comment]
Here you can see my output when I run it with admin rights. Nice! HOWEVER.. These values dont change when stress testing with for example cpu-z. While cpu-z indicates that my temperature is rising due to the stress testing... So that's is still an issue.
![electron_2017-10-03_21-35-06](https://user-images.githubusercontent.com/10887960/31145052-dcad5138-a882-11e7-90cc-b584a92a5287.png)

Greetings Mees

**Comment by sebhildebrandt** [comment]
Thank you once again for testing. This could then be an issue of Windows WMIC. Can you check then if the WMIC command returns other values when stress testing?

**Comment by MeesMaas** [comment]
These values dont know.

**Comment by sebhildebrandt** [comment]
Thank you MessMass! 

So then, if windows refuses to let me know that the temperature changed, it is quite hard to know that something changed, right? Actually I do not know any other reliable source to determine CPU temperature than WMIC (without introducing a bunch of dependencies).

 I will keep it on my list anyway but for now, I will close this issue, OK?

**Comment by swapnilmarathe007** [comment]
Thanks!!
Running my application as admin works.
Is there any way to run it without admin privileges
